<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite name="unittest.loader._FailedTest-20250406154758" tests="1" file="unittest/loader.py" time="0.003" timestamp="2025-04-06T15:47:58" failures="0" errors="1" skipped="0">
		<testcase classname="unittest.loader._FailedTest" name="test" time="0.003" timestamp="2025-04-06T15:47:58" file="/usr/lib/python3.11/unittest/loader.py" line="33">
			<error type="ImportError" message="Failed to import test module: test
Traceback (most recent call last):
  File &quot;/usr/lib/python3.11/unittest/loader.py&quot;, line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/usr/lib/python3.11/unittest/loader.py&quot;, line 350, in _get_module_from_name
    __import__(name)
  File &quot;/home/solarcar/solarcar/Rivanna3/DriverBoard/tests/test.py&quot;, line 6, in &lt;module&gt;
    from gpioPins import DigitalInput, DigitalOutput
  File &quot;/home/solarcar/solarcar/HiL_Testing/Testing_Library/gpioPins.py&quot;, line 3, in &lt;module&gt;
    import Server.config as config
ModuleNotFoundError: No module named 'Server'
"><![CDATA[ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/usr/lib/python3.11/unittest/loader.py", line 407, in _find_test_path
    module = self._get_module_from_name(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/loader.py", line 350, in _get_module_from_name
    __import__(name)
  File "/home/solarcar/solarcar/Rivanna3/DriverBoard/tests/test.py", line 6, in <module>
    from gpioPins import DigitalInput, DigitalOutput
  File "/home/solarcar/solarcar/HiL_Testing/Testing_Library/gpioPins.py", line 3, in <module>
    import Server.config as config
ModuleNotFoundError: No module named 'Server'

]]></error>
		</testcase>
	</testsuite>
</testsuites>
